DROP TABLE IF EXISTS ORG;
CREATE TABLE ORG (
  id BIGINT PRIMARY KEY NOT NULL,
  name  VARCHAR(60),
  parent BIGINT
);


DROP TABLE IF EXISTS PERS;
CREATE TABLE PERS (
  id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title  VARCHAR(30),
  fname  VARCHAR(30),
  name   VARCHAR(60)
);


DROP TABLE IF EXISTS SLOTS;
CREATE TABLE SLOTS (
  id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  pers   BIGINT, -- ref to PERS
  org    BIGINT, -- ref to ORG
  type  VARCHAR(10),
  slot  VARCHAR(60)
);



DROP TABLE IF EXISTS CITIES;
CREATE TABLE CITIES (
  id      BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  nation  CHAR(3) NOT NULL,
  name    VARCHAR(60)
);



DROP TABLE IF EXISTS ADDR;
CREATE TABLE ADDR (
  id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  pers   BIGINT, -- ref to PERS
  org    BIGINT, -- ref to ORG
  -- email  VARCHAR(60),
  nation CHAR(3), -- ref to NATIONS
  city   BIGINT,  -- ref to CITIES
  zip    VARCHAR(10),
  street VARCHAR(80),
  house  INT,
  box    VARCHAR(10)
  -- tel    VARCHAR(30),
  -- fax    VARCHAR(30)
);


DROP TABLE IF EXISTS ORG2ORG;
CREATE TABLE ORG2ORG (
  id1      BIGINT   NOT NULL,
  id2      BIGINT   NOT NULL
);

DROP TABLE IF EXISTS ORG2PERS;
CREATE TABLE ORG2PERS (
  id1      BIGINT   NOT NULL,
  id2      BIGINT   NOT NULL,
  note     VARCHAR(60)
);

