INSERT INTO QUERIES VALUES
       ("LNK1",  "LNK", "Parents by Child",10,NULL);
INSERT INTO QUERIES VALUES
       ("LNK2",  "LNK", "Children by Parent",10,NULL);



DROP TABLE IF EXISTS LNKTYPES;
CREATE TABLE LNKTYPES (
  id       INT   NOT NULL PRIMARY KEY,
  table1   CHAR(20), 
  table2   CHAR(20), 
  label_en VARCHAR(60)
);


DROP TABLE IF EXISTS LNK;
CREATE TABLE LNK (
  lnktype INT,
  id1      BIGINT   NOT NULL,
  id2      BIGINT   NOT NULL,
  note     VARCHAR(60)
);


--INSERT INTO QRYCOLS VALUES
--  ("LNK2",1,"V",NULL,"child","Child", 20,0);
--INSERT INTO QRYCOLS VALUES
--  ("LNK2",2,"F","LNK","note","Note",20,0);
--INSERT INTO QRYCOLS VALUES
--  ("LNK2",3,"F","LNK","id1",NULL,NULL,0);
--INSERT INTO QRYCOLS VALUES
--  ("LNK2",4,"F","LNK","id2",NULL,NULL,0);
--INSERT INTO QRYCOLS VALUES
--  ("LNK2",5,"F","LNK","lnktype",NULL,NULL,0);



-- INSERT INTO QRYCOLS VALUES
--   ("LNK1",1,"V",NULL,"parent","Parent", 20,0);
-- INSERT INTO QRYCOLS VALUES
--   ("LNK1",2,"F","LNK","note","Note",20,0);
-- INSERT INTO QRYCOLS VALUES
--   ("LNK1",3,"F","LNK","id1",NULL,NULL,0);
-- INSERT INTO QRYCOLS VALUES
--   ("LNK1",4,"F","LNK","id2",NULL,NULL,0);
-- INSERT INTO QRYCOLS VALUES
--   ("LNK1",5,"F","LNK","lnktype",NULL,NULL,0);



-- ORG x is member of ORG y
INSERT INTO LNKTYPES VALUES (1,"ORG","ORG","Member");
INSERT INTO LNK VALUES (1,1,2,NULL);
INSERT INTO LNK VALUES (1,1,3,NULL);
INSERT INTO LNK VALUES (1,1,4,NULL);

-- PERS x is contact person of ORG y
INSERT INTO LNKTYPES VALUES (2,"ORG","PERS","Contact person");
INSERT INTO LNK VALUES (2,1,1,NULL);
INSERT INTO LNK VALUES (2,3,1,NULL);
INSERT INTO LNK VALUES (2,2,2,NULL);
INSERT INTO LNK VALUES (2,4,3,NULL);
INSERT INTO LNK VALUES (2,5,4,NULL);


