-- LOC is not used for the moment.

DROP TABLE IF EXISTS LOC_TYPES;

CREATE TABLE LOC_TYPES (
  id       INT PRIMARY KEY NOT NULL,
  name_en  VARCHAR(40)
);

INSERT INTO LOC_TYPES VALUES (1,"Country");
INSERT INTO LOC_TYPES VALUES (2,"Province");
INSERT INTO LOC_TYPES VALUES (3,"Town");
INSERT INTO LOC_TYPES VALUES (4,"Street");
INSERT INTO LOC_TYPES VALUES (5,"Other");

DROP TABLE IF EXISTS LOC;
CREATE TABLE LOC (
  id      BIGINT PRIMARY KEY NOT NULL,
  name_en VARCHAR(60),
  type    INT NOT NULL,
  parent  BIGINT
);

INSERT INTO LOC VALUES (1,"Estonia",1,NULL);
INSERT INTO LOC VALUES (2,"Belgium",1,NULL);
INSERT INTO LOC VALUES (3,"Germany",1,NULL);
INSERT INTO LOC VALUES (4,"France",1,NULL);

INSERT INTO LOC VALUES (5,"Harjumaa",2,1);

INSERT INTO LOC VALUES (6,"Tallinn",3,5);
INSERT INTO LOC VALUES (7,"Tartu",3,1);
INSERT INTO LOC VALUES (8,"Rakvere",3,1);

INSERT INTO LOC VALUES (9,"Eupen",3,2);
INSERT INTO LOC VALUES (10,"Liège",3,2);
INSERT INTO LOC VALUES (11,"Bruxelles",3,2);

INSERT INTO LOC VALUES (12,"Tartu mnt",4,6);
INSERT INTO LOC VALUES (13,"Türnpu",4,6);
INSERT INTO LOC VALUES (14,"Liivalaia",4,6);
INSERT INTO LOC VALUES (15,"Laki",4,6);
INSERT INTO LOC VALUES (16,"Hütte",4,9);

INSERT INTO LOC VALUES (17,"Quartum Center",5,16);


