INSERT INTO ORG VALUES (1,'Lino Partners',NULL);
INSERT INTO ORG VALUES (2,'Girf OÜ',1);
INSERT INTO ORG VALUES (3,'Rumma & Ko OÜ',1);
INSERT INTO ORG VALUES (4,'PAC Systems PGmbH',1);
INSERT INTO ORG VALUES (5,'Microsoft',NULL);
INSERT INTO ORG VALUES (6,'Eesti Telefon',NULL);

INSERT INTO ORG2ORG VALUES (1,2);
INSERT INTO ORG2ORG VALUES (1,3);
INSERT INTO ORG2ORG VALUES (1,4);


INSERT INTO ORG2PERS VALUES (1,1,'Lino author');
INSERT INTO ORG2PERS VALUES (3,1,'2001-2002');
INSERT INTO ORG2PERS VALUES (4,1,'1991-2001');
INSERT INTO ORG2PERS VALUES (2,2,NULL);
INSERT INTO ORG2PERS VALUES (2,5,NULL);
INSERT INTO ORG2PERS VALUES (2,6,NULL);
INSERT INTO ORG2PERS VALUES (4,3,NULL);
INSERT INTO ORG2PERS VALUES (5,4,NULL);

