INSERT INTO PERS VALUES (1,NULL,'Luc','Saffre');
INSERT INTO PERS VALUES (2,NULL,'Andres','Anier');
INSERT INTO PERS VALUES (3,NULL,'Paul','Antys');
INSERT INTO PERS VALUES (4,NULL,'Bill','Gates');
INSERT INTO PERS VALUES (5,NULL,'Hannes','Plinte');
INSERT INTO PERS VALUES (6,NULL,'Marko','Aid');
