INSERT INTO voc_entry (id,word1,word2) VALUES (1,"sous","... all");
INSERT INTO voc_entry (id,word1,word2) VALUES (2,"devant","... ees");
INSERT INTO voc_entry (id,word1,word2) VALUES (3,"pour","... jaoks");
INSERT INTO voc_entry (id,word1,word2) VALUES (4,"sur","... peal");
INSERT INTO voc_entry (id,word1,word2) VALUES (5,"dans","... sees");
INSERT INTO voc_entry (id,word1,word2) VALUES (6,"derrière","... taga");
INSERT INTO voc_entry (id,word1,word2) VALUES (7,"avec","...ga");
INSERT INTO voc_entry (id,word1,word2) VALUES (8,"voilà","„vaata seal“");
INSERT INTO voc_entry (id,word1,word2) VALUES (9,"voici","„vaata siin“");
INSERT INTO voc_entry (id,word1,word2) VALUES (10,"mais","aga");
INSERT INTO voc_entry (id,word1,word2) VALUES (11,"merci","aitäh");
INSERT INTO voc_entry (id,word1,word2) VALUES (12,"fenêtre (n.f.)","aken");
INSERT INTO voc_entry (id,word1,word2) VALUES (13,"gentil / gentille","armas");
INSERT INTO voc_entry (id,word1,word2) VALUES (14,"aimer","armastama");
INSERT INTO voc_entry (id,word1,word2) VALUES (15,"ordinateur (n.m.)","arvuti");
INSERT INTO voc_entry (id,word1,word2) VALUES (16,"voiture (n.f.)","auto");
INSERT INTO voc_entry (id,word1,word2) VALUES (17,"ouvrir (j'ouvre / ouvert)","avama");
INSERT INTO voc_entry (id,word1,word2) VALUES (18,"piscine (n.f.)","bassein");
INSERT INTO voc_entry (id,word1,word2) VALUES (19,"bus (n.m.)","buss");
INSERT INTO voc_entry (id,word1,word2) VALUES (20,"directeur (n.m.)","direktor");
INSERT INTO voc_entry (id,word1,word2) VALUES (21,"non","ei");
INSERT INTO voc_entry (id,word1,word2) VALUES (22,"habiter","elada");
INSERT INTO voc_entry (id,word1,word2) VALUES (23,"salon (n.m.)","elutuba");
INSERT INTO voc_entry (id,word1,word2) VALUES (24,"mère (n.f.)","ema");
INSERT INTO voc_entry (id,word1,word2) VALUES (25,"mauvais / -e","halb");
INSERT INTO voc_entry (id,word1,word2) VALUES (26,"gris / grise","hall");
INSERT INTO voc_entry (id,word1,word2) VALUES (27,"bon / bonne","hea");
INSERT INTO voc_entry (id,word1,word2) VALUES (28,"bonjour","head päeva");
INSERT INTO voc_entry (id,word1,word2) VALUES (29,"bonsoir","head õhtut");
INSERT INTO voc_entry (id,word1,word2) VALUES (30,"bonne nuit","head ööd");
INSERT INTO voc_entry (id,word1,word2) VALUES (31,"Monsieur","Härra");
INSERT INTO voc_entry (id,word1,word2) VALUES (32,"beau / belle","ilus");
INSERT INTO voc_entry (id,word1,word2) VALUES (33,"laid / laide","inetu");
INSERT INTO voc_entry (id,word1,word2) VALUES (34,"père (n.m.)","isa");
INSERT INTO voc_entry (id,word1,word2) VALUES (35,"et","ja");
INSERT INTO voc_entry (id,word1,word2) VALUES (36,"oui","jah");
INSERT INTO voc_entry (id,word1,word2) VALUES (37,"vélo (n.m.)","jalgrattas");
INSERT INTO voc_entry (id,word1,word2) VALUES (38,"courir (je cours / couru)","jooksma");
INSERT INTO voc_entry (id,word1,word2) VALUES (39,"boire (je bois / bu)","jooma");
INSERT INTO voc_entry (id,word1,word2) VALUES (40,"dessiner (je dessine / dessiné)","joonistama");
INSERT INTO voc_entry (id,word1,word2) VALUES (41,"manteau (n.m.)","jope");
INSERT INTO voc_entry (id,word1,word2) VALUES (42,"fromage (n.m.)","juust");
INSERT INTO voc_entry (id,word1,word2) VALUES (43,"fourchette (n.f.)","kahvel");
INSERT INTO voc_entry (id,word1,word2) VALUES (44,"pullover (n.m.)","kampsun");
INSERT INTO voc_entry (id,word1,word2) VALUES (45,"armoire (n.f.)","kapp");
INSERT INTO voc_entry (id,word1,word2) VALUES (46,"plat (n.m.)","kauss");
INSERT INTO voc_entry (id,word1,word2) VALUES (47,"horloge (n.f.)","kell");
INSERT INTO voc_entry (id,word1,word2) VALUES (48,"soulier (n.m.)","king");
INSERT INTO voc_entry (id,word1,word2) VALUES (49,"fermé / fermée","kinni");
INSERT INTO voc_entry (id,word1,word2) VALUES (50,"cinéma (n.m.)","kino");
INSERT INTO voc_entry (id,word1,word2) VALUES (51,"église (n.f.)","kirik");
INSERT INTO voc_entry (id,word1,word2) VALUES (52,"écrire (j'écris / écrit)","kirjutama");
INSERT INTO voc_entry (id,word1,word2) VALUES (53,"verre (n.m.)","klaas");
INSERT INTO voc_entry (id,word1,word2) VALUES (54,"café (n.m.)","kohv");
INSERT INTO voc_entry (id,word1,word2) VALUES (55,"machine à café (n.f.)","kohvimasin");
INSERT INTO voc_entry (id,word1,word2) VALUES (56,"jaune / jaune","kollane");
INSERT INTO voc_entry (id,word1,word2) VALUES (57,"bonbon (n.m.)","komm");
INSERT INTO voc_entry (id,word1,word2) VALUES (58,"école (n.f.)","kool");
INSERT INTO voc_entry (id,word1,word2) VALUES (59,"si … alors","kui … siis");
INSERT INTO voc_entry (id,word1,word2) VALUES (60,"méchant / méchante","kuri");
INSERT INTO voc_entry (id,word1,word2) VALUES (61,"chaud / chaude","kuum");
INSERT INTO voc_entry (id,word1,word2) VALUES (62,"mince / mince","kõhn");
INSERT INTO voc_entry (id,word1,word2) VALUES (63,"dur / dure","kõva");
INSERT INTO voc_entry (id,word1,word2) VALUES (64,"cuisine (n.f.)","köök");
INSERT INTO voc_entry (id,word1,word2) VALUES (65,"froid / froide","külm");
INSERT INTO voc_entry (id,word1,word2) VALUES (66,"demander (je demande / demandé)","küsima");
INSERT INTO voc_entry (id,word1,word2) VALUES (67,"ouvert / ouverte","lahti");
INSERT INTO voc_entry (id,word1,word2) VALUES (68,"table (n.f.)","laud");
INSERT INTO voc_entry (id,word1,word2) VALUES (69,"chanter (je chante / chanté)","laulma");
INSERT INTO voc_entry (id,word1,word2) VALUES (70,"pain (n.m.)","leib");
INSERT INTO voc_entry (id,word1,word2) VALUES (71,"pain complet (n.m.)","leib");
INSERT INTO voc_entry (id,word1,word2) VALUES (72,"avion (n.m.)","lennuk");
INSERT INTO voc_entry (id,word1,word2) VALUES (73,"viande (n.f.)","liha");
INSERT INTO voc_entry (id,word1,word2) VALUES (74,"trop","liiga");
INSERT INTO voc_entry (id,word1,word2) VALUES (75,"limonade (n.f.)","limonaad");
INSERT INTO voc_entry (id,word1,word2) VALUES (76,"ville (n.f.)","linn");
INSERT INTO voc_entry (id,word1,word2) VALUES (77,"cuillère (n.f.)","lusikas");
INSERT INTO voc_entry (id,word1,word2) VALUES (78,"court / courte","lühike");
INSERT INTO voc_entry (id,word1,word2) VALUES (79,"je suis","ma olen");
INSERT INTO voc_entry (id,word1,word2) VALUES (80,"je voudrais","ma tahaksin");
INSERT INTO voc_entry (id,word1,word2) VALUES (81,"chambre à coucher (n.f.)","magamistuba");
INSERT INTO voc_entry (id,word1,word2) VALUES (82,"jus (n.m.)","mahl");
INSERT INTO voc_entry (id,word1,word2) VALUES (83,"maison (n.f.)","maja");
INSERT INTO voc_entry (id,word1,word2) VALUES (84,"machine (n.f.)","masin");
INSERT INTO voc_entry (id,word1,word2) VALUES (85,"nous sommes","me oleme");
INSERT INTO voc_entry (id,word1,word2) VALUES (86,"nous ","meie");
INSERT INTO voc_entry (id,word1,word2) VALUES (87,"métro (n.m.)","metroo");
INSERT INTO voc_entry (id,word1,word2) VALUES (88,"je ","mina");
INSERT INTO voc_entry (id,word1,word2) VALUES (89,"aller (je vais / allé)","minema");
INSERT INTO voc_entry (id,word1,word2) VALUES (90,"compote (n.f.)","moos");
INSERT INTO voc_entry (id,word1,word2) VALUES (91,"j'ai","mul on ");
INSERT INTO voc_entry (id,word1,word2) VALUES (92,"sale / sale","must");
INSERT INTO voc_entry (id,word1,word2) VALUES (93,"noir / noire","must");
INSERT INTO voc_entry (id,word1,word2) VALUES (94,"vendre (je vends / vendu)","müüma");
INSERT INTO voc_entry (id,word1,word2) VALUES (95,"elles ","nad");
INSERT INTO voc_entry (id,word1,word2) VALUES (96,"ils","nad");
INSERT INTO voc_entry (id,word1,word2) VALUES (97,"ils sont","nad on");
INSERT INTO voc_entry (id,word1,word2) VALUES (98,"elles sont","nad on");
INSERT INTO voc_entry (id,word1,word2) VALUES (99,"jeune / jeune","noor");
INSERT INTO voc_entry (id,word1,word2) VALUES (100,"couteau (n.m.)","nuga");
INSERT INTO voc_entry (id,word1,word2) VALUES (101,"au revoir","nägemiseni");
INSERT INTO voc_entry (id,word1,word2) VALUES (102,"oncle (n.m.)","onu");
INSERT INTO voc_entry (id,word1,word2) VALUES (103,"cousin (n.m.)","onupoeg");
INSERT INTO voc_entry (id,word1,word2) VALUES (104,"cousine (n.f.)","onutütar");
INSERT INTO voc_entry (id,word1,word2) VALUES (105,"orange / orange","oranž");
INSERT INTO voc_entry (id,word1,word2) VALUES (106,"acheter","ostma");
INSERT INTO voc_entry (id,word1,word2) VALUES (107,"gros / grosse","paks");
INSERT INTO voc_entry (id,word1,word2) VALUES (108,"s'il vous plaît","palun");
INSERT INTO voc_entry (id,word1,word2) VALUES (109,"s'il te plaît","palun");
INSERT INTO voc_entry (id,word1,word2) VALUES (110,"mettre (je mets / mis)","panema");
INSERT INTO voc_entry (id,word1,word2) VALUES (111,"stylo à bille (n.m.)","pastakas");
INSERT INTO voc_entry (id,word1,word2) VALUES (112,"mou / molle","pehme");
INSERT INTO voc_entry (id,word1,word2) VALUES (113,"lait (n.m.)","piim");
INSERT INTO voc_entry (id,word1,word2) VALUES (114,"long / longue","pikk");
INSERT INTO voc_entry (id,word1,word2) VALUES (115,"poire (n.f.)","pirn");
INSERT INTO voc_entry (id,word1,word2) VALUES (116,"crayon (n.m.)","pliiats");
INSERT INTO voc_entry (id,word1,word2) VALUES (117,"fils (n.m.)","poeg");
INSERT INTO voc_entry (id,word1,word2) VALUES (118,"garçon (n.m.)","poiss");
INSERT INTO voc_entry (id,word1,word2) VALUES (119,"Mademoiselle","Preili");
INSERT INTO voc_entry (id,word1,word2) VALUES (120,"Madame","Proua");
INSERT INTO voc_entry (id,word1,word2) VALUES (121,"brun / brune","pruun");
INSERT INTO voc_entry (id,word1,word2) VALUES (122,"bouteille (n.f.)","pudel");
INSERT INTO voc_entry (id,word1,word2) VALUES (123,"propre / propre","puhas");
INSERT INTO voc_entry (id,word1,word2) VALUES (124,"rouge / rouge","punane");
INSERT INTO voc_entry (id,word1,word2) VALUES (125,"livre (n.m.)","raamat");
INSERT INTO voc_entry (id,word1,word2) VALUES (126,"argent (n.m.)","raha");
INSERT INTO voc_entry (id,word1,word2) VALUES (127,"riche / riche","rikkas");
INSERT INTO voc_entry (id,word1,word2) VALUES (128,"vert / verte","roheline");
INSERT INTO voc_entry (id,word1,word2) VALUES (129,"train (n.m.)","rong");
INSERT INTO voc_entry (id,word1,word2) VALUES (130,"parler (je parle / parlé)","rääkima");
INSERT INTO voc_entry (id,word1,word2) VALUES (131,"tu es","sa oled");
INSERT INTO voc_entry (id,word1,word2) VALUES (132,"salle (n.f.)","saal");
INSERT INTO voc_entry (id,word1,word2) VALUES (133,"pain (blanc) (n.m.)","sai");
INSERT INTO voc_entry (id,word1,word2) VALUES (134,"là","seal");
INSERT INTO voc_entry (id,word1,word2) VALUES (135,"il y a","seal on");
INSERT INTO voc_entry (id,word1,word2) VALUES (136,"c'est","see on");
INSERT INTO voc_entry (id,word1,word2) VALUES (137,"ceci","see siin");
INSERT INTO voc_entry (id,word1,word2) VALUES (138,"jupe (n.f.)","seelik");
INSERT INTO voc_entry (id,word1,word2) VALUES (139,"parce que","sest");
INSERT INTO voc_entry (id,word1,word2) VALUES (140,"ici","siin");
INSERT INTO voc_entry (id,word1,word2) VALUES (141,"tu ","sina");
INSERT INTO voc_entry (id,word1,word2) VALUES (142,"bleu / bleue","sinine");
INSERT INTO voc_entry (id,word1,word2) VALUES (143,"fermer (je ferme / fermé)","sulgema");
INSERT INTO voc_entry (id,word1,word2) VALUES (144,"grand / grande","suur");
INSERT INTO voc_entry (id,word1,word2) VALUES (145,"ami (n.m.)","sõber");
INSERT INTO voc_entry (id,word1,word2) VALUES (146,"amie (n.f.)","sõbranna");
INSERT INTO voc_entry (id,word1,word2) VALUES (147,"chemise (n.f.)","särk");
INSERT INTO voc_entry (id,word1,word2) VALUES (148,"salle à manger (n.f.)","söögituba");
INSERT INTO voc_entry (id,word1,word2) VALUES (149,"manger","sööma");
INSERT INTO voc_entry (id,word1,word2) VALUES (150,"il est ","ta on");
INSERT INTO voc_entry (id,word1,word2) VALUES (151,"elle est ","ta on");
INSERT INTO voc_entry (id,word1,word2) VALUES (152,"taxi (n.m.)","takso");
INSERT INTO voc_entry (id,word1,word2) VALUES (153,"assiette (n.f.)","taldrik");
INSERT INTO voc_entry (id,word1,word2) VALUES (154,"tasse (n.f.)","tass");
INSERT INTO voc_entry (id,word1,word2) VALUES (155,"vous êtes","te olete");
INSERT INTO voc_entry (id,word1,word2) VALUES (156,"savoir (je sais / su)","teadma");
INSERT INTO voc_entry (id,word1,word2) VALUES (157,"thé (n.m.)","tee");
INSERT INTO voc_entry (id,word1,word2) VALUES (158,"vous ","teie");
INSERT INTO voc_entry (id,word1,word2) VALUES (159,"elle","tema");
INSERT INTO voc_entry (id,word1,word2) VALUES (160,"il","tema");
INSERT INTO voc_entry (id,word1,word2) VALUES (161,"salut","tere");
INSERT INTO voc_entry (id,word1,word2) VALUES (162,"bienvenue","tere tulemast");
INSERT INTO voc_entry (id,word1,word2) VALUES (163,"chaise (n.f.)","tool");
INSERT INTO voc_entry (id,word1,word2) VALUES (164,"tarte (n.f.)","tort");
INSERT INTO voc_entry (id,word1,word2) VALUES (165,"chambre (n.f.)","tuba");
INSERT INTO voc_entry (id,word1,word2) VALUES (166,"venir (je viens / venu)","tulema");
INSERT INTO voc_entry (id,word1,word2) VALUES (167,"tante (n.f.)","tädi");
INSERT INTO voc_entry (id,word1,word2) VALUES (168,"fille (n.f.)","tüdruk");
INSERT INTO voc_entry (id,word1,word2) VALUES (169,"fille (n.f.)","tütar");
INSERT INTO voc_entry (id,word1,word2) VALUES (170,"porte (n.f.)","uks");
INSERT INTO voc_entry (id,word1,word2) VALUES (171,"pardon","vabandust");
INSERT INTO voc_entry (id,word1,word2) VALUES (172,"pauvre / pauvre","vaene");
INSERT INTO voc_entry (id,word1,word2) VALUES (173,"blanc / blanche","valge");
INSERT INTO voc_entry (id,word1,word2) VALUES (174,"vieux / vieille","vana");
INSERT INTO voc_entry (id,word1,word2) VALUES (175,"salle de bain (n.f.)","vannituba");
INSERT INTO voc_entry (id,word1,word2) VALUES (176,"vin (n.m.)","vein");
INSERT INTO voc_entry (id,word1,word2) VALUES (177,"frère (n.m.)","vend");
INSERT INTO voc_entry (id,word1,word2) VALUES (178,"eau (n.f.)","vesi");
INSERT INTO voc_entry (id,word1,word2) VALUES (179,"saucisse (n.f.)","vorst");
INSERT INTO voc_entry (id,word1,word2) VALUES (180,"ou","või");
INSERT INTO voc_entry (id,word1,word2) VALUES (181,"peut-être","võib-olla");
INSERT INTO voc_entry (id,word1,word2) VALUES (182,"tartine (n.f.)","võileib");
INSERT INTO voc_entry (id,word1,word2) VALUES (183,"prendre (je prends / pris)","võtma");
INSERT INTO voc_entry (id,word1,word2) VALUES (184,"très","väga");
INSERT INTO voc_entry (id,word1,word2) VALUES (185,"petit /petite","väike");
INSERT INTO voc_entry (id,word1,word2) VALUES (186,"sœur (n.f.)","õde");
INSERT INTO voc_entry (id,word1,word2) VALUES (187,"ballon (n.m.)","õhupall");
INSERT INTO voc_entry (id,word1,word2) VALUES (188,"bière (n.f.)","õlu");
INSERT INTO voc_entry (id,word1,word2) VALUES (189,"professeur (n.m.)","õpetaja");
INSERT INTO voc_entry (id,word1,word2) VALUES (190,"élève (n.m.)","õpilane");
INSERT INTO voc_entry (id,word1,word2) VALUES (191,"pomme (n.f.)","õun");
INSERT INTO voc_entry (id,word1,word2) VALUES (192,"rond / ronde","ümargune");
