hg mv lino.apps.crl.rst              lino.projects.crl.rst
hg mv lino.apps.igen.rst             lino.projects.igen.rst
hg mv lino.apps.rst                  lino.projects.rst
hg mv lino.apps.std.rst              lino.projects.std.rst
hg mv lino.apps.min1.rst             lino.projects.min1.rst
hg mv lino.apps.min2.rst             lino.projects.min2.rst
hg mv lino.apps.presto.rst           lino.projects.presto.rst
hg mv lino.apps.homeworkschool.rst   lino.projects.homeworkschool.rst
hg mv lino.apps.polls_tutorial.rst   lino.projects.polls_tutorial.rst
hg mv lino.apps.cosi.rst             lino.projects.cosi.rst
hg mv lino.apps.cms.rst              lino.projects.cms.rst            