# this file is generated by lino.ui.extjs.ext_ui.ExtUI.generate_dummy_messages()
from django.utils.translation import ugettext
ugettext('Last')
ugettext('Please wait...')
ugettext('Next')
ugettext('Reload current record')
ugettext('First')
ugettext('Previous')
